name: Publish extension
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_extension:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:

      - name: â†©ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ—ï¸ Install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'extension/package-lock.json'

      - name: ğŸ—ï¸ Install packages
        run: cd extension && npm ci

      - name: âš™ï¸ Build extension
        run: cd extension && TARGET=chrome npm run build

      - name: ğŸ—ƒï¸ Compress extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'extension/dist'
          zipFilePath: 'extension/dist/extension.zip'

      - name: ğŸ“¤ Upload extension.zip
        uses: actions/upload-artifact@v3
        with:
          name: extension.zip
          path: 'extension/dist/extension.zip'
          retention-days: 33

  chrome_extension:
    name: Pack Chrome Extension
    runs-on: ubuntu-latest
    needs:
      - build_extension
    steps:

      - name: ğŸ“¥ Download extension.zip
        uses: actions/download-artifact@v3
        with:
          name: extension.zip
          path: .

      - name: ğŸ”‘ Sign Chrome extension
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'extension.zip'
          crxFilePath: 'build/DeDefender.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: ğŸš€ Deploy to pages branch
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/main'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          BASE_BRANCH: main
          clean: false
          single-commit: true

  firefox_addon:
    name: Pack FireFox addon
    runs-on: ubuntu-latest
    needs:
      - build_extension
    steps:

      - name: ğŸ“¥ Download extension.zip
        uses: actions/download-artifact@v3
        with:
          name: extension.zip
          path: .

      - name: ğŸ”‘ Sign FireFox extension
        id: ffSignXpi
        continue-on-error: true
        uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@v1
        with:
          timeoutMs: 1200000
          extensionId: ${{ secrets.FF_OFFLINE_EXT_ID }}
          zipFilePath: 'extension.zip'
          xpiFilePath: 'build/DeDefender.xpi'
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}

      - name: ğŸ”‘ Sign error?
        if: |
          steps.ffSignXpi.outcome == 'failure' &&
          steps.ffSignXpi.outputs.sameVersionAlreadyUploadedError != 'true'
        run: exit 1

      - name: ğŸš€ Deploy to pages branch
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/main'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          BASE_BRANCH: main
          clean: false
          single-commit: true
